[[profile]]
name = "builtin LCD"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=0x0631", "s=", "v=LG Display"]
mode = "1920x1080@59.999Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Desk Home (second)"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=DELL U2212HM", "s=Y9KCH19K00PL", "v=Dell Inc."]
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=0x0631", "s=", "v=LG Display"]
mode = "1920x1080@59.999Hz"
position = "0,1080"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Desk Home"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = false
search = ["m=PHL 276E8V", "v=Philips Consumer Electronics Company"]

[[profile.output]]
enable = true
search = ["m=DELL U2723QE", "s=GS054P3", "v=Dell Inc."]
mode = "3840x2160@59.997002Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=0x0631", "s=", "v=LG Display"]
mode = "1920x1080@59.999Hz"
position = "3840,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Desk Home (fixed?)"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=DELL U2723QE", "s=GS054P3", "v=Dell Inc."]
mode = "3840x2160@59.997002Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=0x0631", "s=", "v=LG Display"]
mode = "1920x1080@59.999Hz"
position = "3840,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

